# Generated by Django 4.2.10 on 2024-02-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0002_remove_cart_price_remove_cart_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='menuitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DeliveryApp.menuitem'),
        ),
    ]
