# Generated by Django 4.2.10 on 2024-02-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0004_alter_cart_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
    ]
