# Generated by Django 4.2.10 on 2024-02-27 16:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DeliveryApp', '0005_remove_orderitem_price_remove_orderitem_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('user', 'menuitem')},
        ),
    ]
