# Generated by Django 4.2.10 on 2024-03-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0007_cart_price_cart_unit_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.order'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menuitem')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
